apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
        - name: {{.Values.app.name}}
          imagePullPolicy: Always
          image: {{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "{{.Values.postgres.DBHOST}}"
            - name: DBUSER
              value: "{{.Values.postgres.DBUSER}}"
            - name: DBPASS
              value: "{{.Values.postgres.DBPASS}}"
            - name: DBPORT
              value: "{{.Values.postgres.DBPORT}}"
            - name: DBNAME
              value: "{{.Values.postgres.DBNAME}}"