apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.postgres.DBPORT}}
      targetPort: {{.Values.postgres.DBPORT}}
      
  selector:
    app: postgresdb
  type: LoadBalancer