apiVersion: v1
kind: Service
metadata:
  labels:
    app: peopleapi
  name: peopleapi
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: peopleapi
status:
  loadBalancer: {}
